ci: update dist-check workflow for pnpm workspace

diff --git a/.github/workflows/dist-check.yaml b/.github/workflows/dist-check.yaml
--- a/.github/workflows/dist-check.yaml
+++ b/.github/workflows/dist-check.yaml
@@ -4,11 +4,7 @@ name: Dist check
 
 on:
   pull_request:
-    branches:
-      - main
   push:
-    branches:
-      - main
 
 permissions:
   contents: read
@@ -25,27 +21,19 @@ jobs:
       - name: Build dist/ directories
         run: pnpm build
 
-      # This will fail the workflow if the `dist/` directory is different than
-      # expected.
+      # This will fail the workflow if the committed `dist/` directory is
+      # different than the build output.
       - name: Compare directories
-        id: diff
         run: |
-          if [ ! -d dist/ ]; then
-            echo "Expected dist/ directory does not exist. See status below:"
-            ls -la ./
-            exit 1
-          fi
-          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
-            echo "Detected uncommitted changes after build. See status below:"
-            git diff --ignore-space-at-eol --text dist/
-            exit 1
-          fi
+          # Find all subdirectories that contain a dist/ folder.
+          PACKAGES=$(find . -maxdepth 2 -type d -name "dist")
 
-      # If `dist/` was different than expected, upload the expected version as a
-      # workflow artifact.
-      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
-        name: Upload artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: dist
-          path: dist/
+          for pkg in $PACKAGES; do
+            echo "Checking dist/ directory in $pkg..."
+
+            if [ "$(git diff --ignore-space-at-eol --text $pkg | wc -l)" -gt "0" ]; then
+              echo "Detected uncommitted changes in $pkg. See status below:"
+              git diff --ignore-space-at-eol --text $pkg
+              exit 1
+            fi
+          done
